#!/usr/bin/tclsh

# First, get to the toplevel git dir

set sub [exec git rev-parse --show-toplevel]
cd $sub

# Now extract the exact name of the submodule view directory
set dirname [lindex [file split [pwd]] end]

# Ok, now go to the upper dir...
cd ..

# and try again with git top. If fails, it's not a submodule.

if { [catch {set top [exec git rev-parse --show-toplevel]} err] } {
	puts stderr "Looxlike '$sub' is not a submodule directory"
	puts stderr $err
	exit 1
}

# Don't change dir to this dir though. Read from the current dir.

set sublist [exec git ls-tree HEAD]


foreach l [split $sublist \n] {
	lassign $l rights type hash name
	if { $name == $dirname } {
		puts $hash
		exit 0
	}
}

puts stderr "WEIRD - '$dirname' not found in the tree list:\n$sublist"
exit 1

