#!/usr/bin/tclsh

if { [catch {exec git rev-parse --show-toplevel} toplevel] } {
	puts "git-topic: Not in a git repository"
	exit 1
}

# Search for files: .gittopic, .topic, TOPIC
# If begins with [...] then this holds the branch name.

set names {.gittopic .topic TOPIC}

foreach n $names {
	if { [file exists $n] } {
		# Load topic
		set fd [open $n r]
		while { [gets $fd line] != -1} {
			set line [string trim $line]
			if { [string index $line 0] == "\[" } {
				set e [string first "\]" $line]
				if { $e == -1 } {
					puts "($n: invalid syntax)"
					exit 1
				}
				set brname [string range $line 1 $e-1]
				set toptext([string trim $brname]) [string trim [string range $line $e+1 end]]
			} else {
				set toptext(default) $line
			}
		}
		close $fd
		set curbr [exec git branch | grep ^* | cut -c 3-]
		if { [info exists toptext($curbr)] } {
			puts $toptext($curbr)
		} elseif { [info exists toptext(default)] } {
			puts $toptext(default)
		} else {
			puts "No topic for $curbr"
		}
		exit 0
	}
}

puts "No topic file found ($names)"
